image: node

stages:
  - deploy

deploy:
  stage: deploy
  type: deploy
  image : ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=crmApp-api --api-key=$HEROKU_STAGING_API_KEY
  when: manual
  only:
    - master
